using BlazeKit.Abstraction;
using System;
using System.Linq;
using System.Text;

namespace BlazeKit.Routes.Pages.SourceTemplates
{
    /// <summary>
    /// A generated source code of a route class
    /// </summary>
    internal class RouteClassSource : Lazy<string>
    {
        /// <summary>
        /// A generated source code of a route class
        /// </summary>
        public RouteClassSource(string classNameSpace, string className, string route, string layout, params string[] parameters) : base(() =>
        {
            var text = new StringBuilder();
            text.AppendLine($"// Auto-generated by BlazeKit");
            text.AppendLine("using Microsoft.AspNetCore.Components;");
            text.AppendLine("using BlazeKit.Abstraction;");
            text.AppendLine($"namespace {classNameSpace};");
            text.AppendLine($"[Route(\"{(route == "" ? "/" : route)}\")]");

            if (!string.IsNullOrEmpty(layout))
            {
                text.AppendLine($"[Layout(typeof({layout}))]");
            }

            if (parameters.Count() > 0)
            {
                text.AppendLine($"public partial class {className} {{");
                text.AppendLine("\t// Route Params");
                foreach (var parameter in parameters)
                {
                    text.AppendLine("\t[Parameter]");
                    text.AppendLine($"\tpublic string {parameter} {{ get; set;}}");
                }
                //text.AppendLine("\tpublic void Update() => InvokeAsync(StateHasChanged);");
                text.AppendLine("}");
            }
            else
            {
                text.AppendLine($"public partial class {className} {{");
                //text.AppendLine("\tpublic void Update() => InvokeAsync(StateHasChanged);");
                text.AppendLine("}");
            }


            return text.ToString();
        })
        {

        }
    }
}
