using System.Reflection;
using System.Text;

namespace BlazeKit.Routes.Pages.SourceTemplates;

/// <summary>
/// A generated source code of a route class
/// </summary>
public class SitemapClassSource : Lazy<string>
{
    /// <summary>
    /// A generated source code of a route class
    /// </summary>
    public SitemapClassSource(string classNameSpace, string className, List<Tuple<string,string>> headers) : base(() =>
    {
        var sb = new StringBuilder();
        var lst = new List<string>();
        foreach (var (title, link) in headers)
        {
            // sb.AppendLine($@"{{ ""{title}"", ""{header.Value}"" }}");
            lst.Add($@"new Tuple<string,string>(""{title}"", ""{link}"")");
        }

        return @$"
            // Auto-generated by BlazeKit
            namespace {classNameSpace};
            public class {className}
            {{
                public List<Tuple<string, string>> Headers {{ get; }}

                public {className}()
                {{
                    Headers = new List<Tuple<string, string>>() {{
                        {string.Join(",",lst)}
                    }};
                }}
            }}
        ";
    })
    {

    }
}
